media:
  - name: videos
    label: 'Videos'
    input: static/assets/videos
    output: /assets/videos
    categories: [ video ]
  - name: images
    label: 'Images'
    input: assets/images/uploads
    output: /images/uploads
    categories: [ image ]

content:
- fields:
  - fields:
    - i18n: true
      label: Title
      name: title
      required: false
      type: string
    - i18n: true
      label: URL
      name: url
      required: false
      type: string
    - i18n: true
      label: Is blank?
      name: blank
      required: false
      type: boolean
    - i18n: true
      label: Is highlighted?
      name: is_highlighted
      required: false
      type: boolean
    - fields:
      - i18n: true
        label: Title
        name: title
        required: false
        type: string
      - i18n: true
        label: URL
        name: url
        required: false
        type: string
      - i18n: true
        label: Is blank?
        name: blank
        required: false
        type: boolean
      i18n: true
      label: Links
      label_singular: Link
      list: true
      name: links
      required: false
      type: object
    i18n: true
    label: Links
    label_singular: Link
    list: true
    name: links
    required: false
    type: object
  i18n: true
  label: Primary navigation
  name: primary
  path: data/menu/primary.yml
  type: file
- fields:
  - fields:
    - i18n: true
      label: Title
      name: title
      required: false
      type: string
    - i18n: true
      label: URL
      name: url
      required: false
      type: string
    - i18n: true
      label: Is blank?
      name: blank
      required: false
      type: boolean
    - i18n: true
      label: Is highlighted?
      name: is_highlighted
      required: false
      type: boolean
    - fields:
      - i18n: true
        label: Title
        name: title
        required: false
        type: string
      - i18n: true
        label: URL
        name: url
        required: false
        type: string
      - i18n: true
        label: Is blank?
        name: blank
        required: false
        type: boolean
      i18n: true
      label: Links
      label_singular: Link
      list: true
      name: links
      required: false
      type: object
    i18n: true
    label: Links
    label_singular: Link
    list: true
    name: links
    required: false
    type: object
  i18n: true
  label: Legals navigation (mentions, policy…)
  name: legal
  path: data/menu/legal.yml
  type: file
- fields:
  - fields:
    - i18n: true
      label: Title
      name: title
      required: false
      type: string
    - i18n: true
      label: URL
      name: url
      required: false
      type: string
    - i18n: true
      label: Is blank?
      name: blank
      required: false
      type: boolean
    - i18n: true
      label: Is highlighted?
      name: is_highlighted
      required: false
      type: boolean
    - fields:
      - i18n: true
        label: Title
        name: title
        required: false
        type: string
      - i18n: true
        label: URL
        name: url
        required: false
        type: string
      - i18n: true
        label: Is blank?
        name: blank
        required: false
        type: boolean
      i18n: true
      label: Links
      label_singular: Link
      list: true
      name: links
      required: false
      type: object
    i18n: true
    label: Links
    label_singular: Link
    list: true
    name: links
    required: false
    type: object
  i18n: true
  label: Socials navigation
  name: social
  path: data/menu/social.yml
  type: file
- fields:
  - i18n: true
    label: Title
    name: title
    required: false
    type: string
  - i18n: true
    label: Text
    name: text
    required: false
    type: text
  - collapsed: true
    fields:
    - i18n: true
      label: Text
      name: text
      required: false
      type: string
    - i18n: true
      label: URL
      name: url
      required: false
      type: string
    - description: Enter code lang (e.g. fr) if different of the current page language
      i18n: true
      label: Language
      name: lang
      required: false
      type: string
    - i18n: true
      label: Is blank?
      name: blank
      required: false
      type: boolean
    i18n: true
    label: CTA
    name: cta
    required: false
    summary: '{{text}}'
    type: object
  i18n: true
  label: Information text at the bottom of the site
  name: footer
  path: data/footer.yml
  type: file
- fields:
  - i18n: true
    label: Title
    name: title
    required: false
    type: string
  - description: Displayed in tabs, search results, and in SMS/Messages/Social networks
      preview
    i18n: true
    label: Description
    name: description
    required: false
    type: text
  - choose_url: false
    description: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
    i18n: true
    label: Image
    name: src
    options:
      media: images
    required: false
    type: image
  - description: Username
    i18n: duplicate
    label: Twitter/X
    name: twitter
    required: false
    type: string
  i18n: true
  label: Global SEO
  name: seo
  path: data/seo.yml
  type: file
- create: true
  description: All pages
  editor:
    preview: false
  fields:
  - default: true
    i18n: true
    label: Draft
    name: draft
    required: false
    type: boolean
  - description: Displayed in tabs, search results, and in SMS/Messages/Social networks
      preview
    i18n: true
    label: Page title
    name: title
    required: true
    type: string
  - description: Displayed in tabs, search results, and in SMS/Messages/Social networks
      preview
    i18n: true
    label: Description
    name: description
    required: false
    type: text
  - collapsed: true
    fields:
    - i18n: true
      label: Title
      name: title
      required: false
      type: string
    - buttons:
      - bold
      - italic
      - link
      - bulleted-list
      editor_components: []
      i18n: true
      label: Text
      minimal: true
      modes:
      - rich_text
      name: text
      required: false
      type: rich-text
    - collapsed: true
      fields:
      - choose_url: false
        description: Video (MP4)
        i18n: duplicate
        label: MP4
        name: mp4
        options:
          extensions:
          - mp4
          media: videos
        required: false
        type: file
      - choose_url: false
        description: Video (WEBM)
        i18n: duplicate
        label: WEBM
        name: webm
        options:
          extensions:
          - webm
          media: videos
        required: false
        type: file
      - choose_url: false
        description: Video (MP4)
        i18n: duplicate
        label: Mobile MP4
        name: mp4_mobile
        options:
          extensions:
          - mp4
          media: videos
        required: false
        type: file
      - choose_url: false
        description: Video (WEBM)
        i18n: duplicate
        label: Mobile WEBM
        name: webm_mobile
        options:
          extensions:
          - webm
          media: videos
        required: false
        type: file
      i18n: true
      label: Videos
      name: video
      required: false
      type: object
    i18n: true
    label: Hero
    name: hero
    required: false
    type: object
  - blockKey: type
    blocks:
    - collapsed: false
      fields:
      - collapsed: true
        fields:
        - i18n: true
          label: Surtitle
          name: surtitle
          required: false
          type: string
        - i18n: true
          label: Title
          name: title
          required: false
          type: string
        - buttons:
          - bold
          - italic
          - link
          - bulleted-list
          editor_components: []
          i18n: true
          label: Text
          minimal: true
          modes:
          - rich_text
          name: text
          required: false
          type: rich-text
        i18n: true
        label: Heading
        name: heading
        required: false
        summary: '{{title}}'
        type: object
      - allow_add: true
        collapsed: true
        fields:
        - i18n: true
          label: Text
          name: text
          required: false
          type: string
        - i18n: true
          label: URL
          name: url
          required: false
          type: string
        - description: Enter code lang (e.g. fr) if different of the current page
            language
          i18n: true
          label: Language
          name: lang
          required: false
          type: string
        - i18n: true
          label: Is blank?
          name: blank
          required: false
          type: boolean
        i18n: true
        label: CTAs
        label_singular: CTA
        list: true
        max: 2
        min: 0
        name: ctas
        required: false
        summary: '{{fields.text}}'
        type: object
      - default: false
        i18n: duplicate
        label: With a background?
        name: background
        required: false
        type: boolean
      i18n: true
      label: Call to action
      name: cta
      required: false
      summary: '{{cta.text}}'
      type: object
    - collapsed: false
      fields:
      - collapsed: true
        fields:
        - i18n: true
          label: Surtitle
          name: surtitle
          required: false
          type: string
        - i18n: true
          label: Title
          name: title
          required: false
          type: string
        - buttons:
          - bold
          - italic
          - link
          - bulleted-list
          editor_components: []
          i18n: true
          label: Text
          minimal: true
          modes:
          - rich_text
          name: text
          required: false
          type: rich-text
        i18n: true
        label: Heading
        name: heading
        required: false
        summary: '{{title}}'
        type: object
      - description: ""
        i18n: duplicate
        label: Grid
        name: grid
        options:
          values:
          - label: Small
            value: small
          - label: Medium
            value: medium
          - label: Large
            value: large
          - label: Container
            value: container
          - label: Full
            value: full
        required: true
        type: select
      - description: ""
        i18n: duplicate
        label: Offset
        name: offset
        options:
          values:
          - label: Start
            value: start
          - label: Center
            value: center
          - label: End
            value: end
        required: false
        type: select
      - i18n: true
        label: Name
        name: name
        required: false
        type: string
      - i18n: true
        label: Send button text
        name: submit
        required: false
        type: string
      - collapsed: true
        fields:
        - i18n: true
          label: Label
          name: label
          required: false
          type: string
        - i18n: true
          label: Name
          name: name
          required: false
          type: string
        - description: Choose type field
          i18n: duplicate
          label: Type
          name: type
          options:
            values:
            - label: Email
              value: email
            - label: Checkbox
              value: checkbox
            - label: Radio
              value: radio
            - label: Select
              value: select
            - label: Tel
              value: tel
            - label: Text
              value: text
            - label: Textarea
              value: textarea
          required: false
          type: select
        - description: Only for select fields
          fields:
          - i18n: true
            label: Title
            name: title
            required: false
            type: string
          - i18n: true
            label: Value
            name: value
            required: false
            type: string
          i18n: true
          label: Options
          label_singular: Option
          list: true
          name: options
          required: false
          type: object
        - description: Only for checkbox and radio fields
          i18n: true
          label: Value
          name: value
          required: false
          type: string
        - i18n: duplicate
          label: Required
          name: required
          required: false
          type: boolean
        - i18n: duplicate
          label: Full width field?
          name: full
          required: false
          type: boolean
        - i18n: true
          label: Placeholder
          name: placeholder
          required: false
          type: string
        - description: ""
          i18n: duplicate
          label: Autocomplete
          name: autocomplete
          options:
            values:
            - label: Email
              value: email
            - label: Tel
              value: tel
            - label: Title
              value: honorific-prefix
            - label: Firstname
              value: given-name
            - label: Lastname
              value: family-name
            - label: Name
              value: name
            - label: Street
              value: street-address
            - label: Address level1
              value: address-level1
            - label: Address level2
              value: address-level2
            - label: Postal code
              value: postal-code
            - label: Country name
              value: country-name
            - label: Organization
              value: organization
          required: false
          type: select
        i18n: true
        label: Fields
        label_singular: Field
        list: true
        name: items
        required: false
        summary: '{{label}}'
        type: object
      - collapsed: true
        fields:
        - choose_url: false
          description: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
          i18n: true
          label: Image
          name: src
          options:
            media: images
          required: false
          type: image
        - description: For an image that conveys information (leave blank if decorative
            image)
          i18n: true
          label: Text alternative
          name: alt
          required: false
          type: string
        - buttons:
          - link
          editor_components: []
          i18n: true
          label: Credit
          minimal: true
          modes:
          - rich_text
          name: credit
          required: false
          type: rich-text
        i18n: true
        label: Images
        name: image
        required: false
        type: object
      i18n: true
      label: Form
      name: form
      required: false
      summary: '{{heading.title}}'
      type: object
    - collapsed: false
      fields:
      - i18n: true
        label: Surtitle
        name: surtitle
        required: false
        type: string
      - i18n: true
        label: Title
        name: title
        required: false
        type: string
      - buttons:
        - bold
        - italic
        - link
        - bulleted-list
        editor_components: []
        i18n: true
        label: Text
        minimal: true
        modes:
        - rich_text
        name: text
        required: false
        type: rich-text
      i18n: true
      label: Paragraph
      name: paragraph
      required: false
      summary: '{{title}}'
      type: object
    collapsed: false
    i18n: true
    label: Blocs
    label_singular: Bloc
    list: true
    name: blocks
    required: false
    type: block
  filename: '{fields.title}/_index.md'
  i18n: true
  label: Pages
  label_singular: Page
  name: pages
  path: content
  type: collection

