settings:
  hide: true

media:
  - name: images
    label: 'Images'
    input: /assets/images/uploads
    output: /images/uploads
    categories: [ image ]
  - name: videos
    label: 'Videos'
    input: /static/assets/videos
    output: /assets/videos
    categories: [ video ]
  


content:
- fields:
  - fields:
    - label: Title
      name: title
      required: false
      type: string
    - label: URL
      name: url
      required: false
      type: string
    - label: Is blank?
      name: blank
      required: false
      type: boolean
    label: Links
    list: true
    name: links
    required: false
    type: object
  i18n: true
  label: Legals navigation (mentions, policy…)
  name: legal
  path: data/menu/legal.yml
  type: file
- fields:
  - label: Title
    name: title
    required: false
    type: string
  - label: Text
    name: text
    required: false
    type: text
  - fields:
    - label: Text
      name: text
      required: false
      type: string
    - label: URL
      name: url
      required: false
      type: string
    - label: Is blank?
      name: blank
      required: false
      type: boolean
    label: CTA
    name: cta
    required: false
    type: object
  i18n: true
  label: Information text at the bottom of the site
  name: footer
  path: data/footer.yml
  type: file
- fields:
  - label: Title
    name: title
    required: false
    type: string
  - description: Displayed in tabs, search results, and in SMS/Messages/Social networks preview
    label: Description
    name: description
    required: false
    type: text
  - description: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
    label: Image
    name: src
    options:
      media: images
    required: false
    type: image
  - description: Username
    label: Twitter/X
    name: twitter
    required: false
    type: string
  i18n: true
  label: Global SEO
  name: seo
  path: data/seo.yml
  type: file
- description: All pages
  fields:
  - default: true
    label: Draft
    name: draft
    required: false
    type: boolean
  - description: Displayed in tabs, search results, and in SMS/Messages/Social networks preview
    label: Page title
    name: title
    required: true
    type: string
  - description: Displayed in tabs, search results, and in SMS/Messages/Social networks preview
    label: Description
    name: description
    required: false
    type: text
  - fields:
    - label: Title
      name: title
      required: false
      type: string
    - label: Text
      name: text
      options:
        media: false
      required: false
      type: rich-text
    - fields:
      - default: false
        label: Is background?
        name: background
        required: false
        type: boolean
      - description: MP4 video file
        label: MP4
        name: mp4
        options:
          extensions:
          - mp4
          media: videos
        required: false
        type: file
      - description: WEBM video file
        label: WEBM
        name: webm
        options:
          extensions:
          - webm
          media: videos
        required: false
        type: file
      - description: MP4 video file for mobile
        label: MP4 (Mobile)
        name: mp4_mobile
        options:
          extensions:
          - mp4
          media: videos
        required: false
        type: file
      - description: WEBM video file for mobile
        label: WEBM (Mobile)
        name: webm_mobile
        options:
          extensions:
          - webm
          media: videos
        required: false
        type: file
      label: Video
      name: video
      required: false
      type: object
    - fields:
      - label: Text
        name: text
        required: false
        type: string
      - description: MP4 video file
        label: MP4
        name: mp4
        options:
          extensions:
          - mp4
          media: videos
        required: false
        type: file
      - description: WEBM video file
        label: WEBM
        name: webm
        options:
          extensions:
          - webm
          media: videos
        required: false
        type: file
      - description: MP4 video file for mobile
        label: MP4 (Mobile)
        name: mp4_mobile
        options:
          extensions:
          - mp4
          media: videos
        required: false
        type: file
      - description: WEBM video file for mobile
        label: WEBM (Mobile)
        name: webm_mobile
        options:
          extensions:
          - webm
          media: videos
        required: false
        type: file
      label: Modal video
      name: video_modal
      required: false
      type: object
    label: Hero
    name: hero
    required: false
    type: object
  - blockKey: type
    blocks:
    - fields:
      - label: Direction
        name: direction
        options:
          values:
          - label: Ltr
            value: ltr
          - label: Rtl
            value: rtl
        required: false
        type: select
      - label: Surtitle
        name: surtitle
        required: false
        type: string
      - label: Title
        name: title
        required: false
        type: string
      - label: Text
        name: text
        options:
          media: false
        required: false
        type: rich-text
      - fields:
        - description: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
          label: Image
          name: src
          options:
            media: images
          required: false
          type: image
        - description: For an image that conveys information (leave blank if decorative image)
          label: Text alternative
          name: alt
          required: false
          type: string
        - label: Credit
          name: credit
          options:
            media: false
          required: false
          type: rich-text
        label: Images
        name: image
        required: false
        type: object
      label: Editorial
      name: editorial
      required: false
      type: object
    - fields:
      - fields:
        - label: Surtitle
          name: surtitle
          required: false
          type: string
        - label: Title
          name: title
          required: false
          type: string
        - label: Text
          name: text
          options:
            media: false
          required: false
          type: rich-text
        label: Heading
        name: heading
        required: false
        type: object
      - default: large
        label: Grid
        name: grid
        options:
          values:
          - label: Small
            value: small
          - label: Medium
            value: medium
          - label: Large
            value: large
          - label: Container
            value: container
          - label: Full
            value: full
        required: true
        type: select
      - label: Offset
        name: offset
        options:
          values:
          - label: Start
            value: start
          - label: Center
            value: center
          - label: End
            value: end
        required: false
        type: select
      - label: Name
        name: name
        required: false
        type: string
      - label: Send button text
        name: submit
        required: false
        type: string
      - fields:
        - label: Label
          name: label
          required: false
          type: string
        - label: Name
          name: name
          required: false
          type: string
        - default: text
          label: Type
          name: type
          options:
            values:
            - label: Email
              value: email
            - label: Checkbox
              value: checkbox
            - label: Radio
              value: radio
            - label: Select
              value: select
            - label: Tel
              value: tel
            - label: Text
              value: text
            - label: Textarea
              value: textarea
          required: true
          type: select
        - description: Only for select fields
          fields:
          - label: Title
            name: title
            required: false
            type: string
          - label: Value
            name: value
            required: false
            type: string
          label: Options
          list: true
          name: items
          required: false
          type: object
        - description: Only for checkbox and radio fields
          label: Value
          name: value
          required: false
          type: string
        - label: Required
          name: required
          required: false
          type: boolean
        - label: Full width field?
          name: full
          required: false
          type: boolean
        - label: Placeholder
          name: placeholder
          required: false
          type: string
        - label: Autocomplete
          name: autocomplete
          options:
            values:
            - label: Email
              value: email
            - label: Tel
              value: tel
            - label: Title
              value: honorific-prefix
            - label: Firstname
              value: given-name
            - label: Lastname
              value: family-name
            - label: Name
              value: name
            - label: Street
              value: street-address
            - label: Address level1
              value: address-level1
            - label: Address level2
              value: address-level2
            - label: Postal code
              value: postal-code
            - label: Country name
              value: country-name
            - label: Organization
              value: organization
          required: false
          type: select
        label: Fields
        list: true
        name: items
        required: false
        type: object
      label: Form
      name: form
      required: false
      type: object
    - fields:
      - label: Surtitle
        name: surtitle
        required: false
        type: string
      - label: Title
        name: title
        required: false
        type: string
      - label: Text
        name: text
        options:
          media: false
        required: false
        type: rich-text
      - description: 'To link a word in the text to a note, suffix it with "[\*]". Notes and "[\*]" are linked by their order.'
        fields:
        - label: Text
          name: text
          required: false
          type: string
        label: Notes
        list: true
        name: notes
        required: false
        type: object
      - fields:
        - label: Text
          name: text
          required: false
          type: string
        - label: URL
          name: url
          required: false
          type: string
        - description: Enter code lang (e.g. fr) if different of the current page language
          label: Language
          name: lang
          required: false
          type: string
        - label: Is blank?
          name: blank
          required: false
          type: boolean
        label: CTAs
        list:
          max: 2
        name: ctas
        required: false
        type: object
      - default: large
        label: Grid
        name: grid
        options:
          values:
          - label: Small
            value: small
          - label: Medium
            value: medium
          - label: Large
            value: large
          - label: Container
            value: container
          - label: Full
            value: full
        required: true
        type: select
      - label: Offset
        name: offset
        options:
          values:
          - label: Start
            value: start
          - label: Center
            value: center
          - label: End
            value: end
        required: false
        type: select
      - label: Alignment
        name: align
        options:
          values:
          - label: Start
            value: start
          - label: Center
            value: center
          - label: End
            value: end
        required: false
        type: select
      - default: false
        label: With a background?
        name: background
        required: false
        type: boolean
      label: Paragraph
      name: paragraph
      required: false
      type: object
    - fields:
      - fields:
        - label: Surtitle
          name: surtitle
          required: false
          type: string
        - label: Title
          name: title
          required: false
          type: string
        - label: Text
          name: text
          options:
            media: false
          required: false
          type: rich-text
        label: Heading
        name: heading
        required: false
        type: object
      - fields:
        - description: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
          label: Image
          name: src
          options:
            media: images
          required: false
          type: image
        - description: For an image that conveys information (leave blank if decorative image)
          label: Text alternative
          name: alt
          required: false
          type: string
        - label: Credit
          name: credit
          options:
            media: false
          required: false
          type: rich-text
        label: Images
        name: image
        required: false
        type: object
      - fields:
        - default: false
          label: Is background?
          name: background
          required: false
          type: boolean
        - description: MP4 video file
          label: MP4
          name: mp4
          options:
            extensions:
            - mp4
            media: videos
          required: false
          type: file
        - description: WEBM video file
          label: WEBM
          name: webm
          options:
            extensions:
            - webm
            media: videos
          required: false
          type: file
        - description: MP4 video file for mobile
          label: MP4 (Mobile)
          name: mp4_mobile
          options:
            extensions:
            - mp4
            media: videos
          required: false
          type: file
        - description: WEBM video file for mobile
          label: WEBM (Mobile)
          name: webm_mobile
          options:
            extensions:
            - webm
            media: videos
          required: false
          type: file
        label: Video
        name: video
        required: false
        type: object
      label: Title
      name: title
      required: false
      type: object
    label: Blocs
    list: true
    name: blocks
    required: false
    type: block
  filename: '{fields.title}/_index.md'
  i18n: true
  label: Pages
  label_singular: Page
  name: pages
  path: content
  type: collection


